config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users
  resources :transactions
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
    @users = User.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @options =  User.all.collect {|user| [user.name, user.id]}
  end

  def create
    @account = Account.new(account_params)
    @account.save
    redirect_to @account
  end



  private
  def account_params
    params.require(:account).permit(:user_id, :total)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
    @users = User.all
    @accounts = Account.all
  end

  def show
    @transaction = Transaction.find(params[:id])
    @account = Account.find(@transaction.account_id)
    @user = User.find(@account.user_id)
    @NOMINALS = [100, 50, 20, 10, 5, 1]
    @bill_types = []
      def dispense(amount)
        @NOMINALS.each do |denomination|
          @bill_types.push([amount/denomination, denomination])
          amount = amount % denomination
        end
        return @bill_types
      end
      @response = dispense(@transaction.amount).delete_if {|item| item[0].zero?}
      #@account.total -= @transaction.amount
      #@account.save
  end
  def new
      @users = User.all
      @options =  Account.all.collect {|account| ["#{@users.find(account.user_id).name} " + "Account Number " + "#{account.id}", account.id]}
  end

  def create
    @transaction = Transaction.new(user_params)

    @transaction.save
    redirect_to @transaction
  end

  private
  def user_params
    params.require(:transaction).permit(:amount, :account_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    @user = User.new(user_params)

    @user.save
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Account Number</th>
    <th>Account Holder</th>
    <th>Total</th>
  </tr>

  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.id %></td>
      <td><%= @users.find(account.user_id).name %></td>
      <td>$<%= account.total %></td>
      <td><%= link_to 'Show', account_path(account) %></td>
    </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= form_for :account, url: accounts_path do |account_form| %>
  <p>
    Account Owner<br>
    <%= account_form.select :user_id, @options %>
  </p>

  <p>
    <%= account_form.label :total %><br>
    <%= account_form.number_field :total %>
  </p>

  <p>
    <%= account_form.submit %>
  </p>
<% end %>

app/views/accounts/show.html.erb
<p>
  <strong>New Account:</strong>
  <%= @account.id %>
</p>

<p>
  <strong>User Number:</strong>
  <%= @account.user_id %>
</p>

<p>
  <strong> Total Deposit:</strong>
  <%= @account.total %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashDispenserRor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<h1>List of Transactions</h1>

<table>
  <tr>
    <th>Account Number</th>
    <th>Account Holder</th>
    <th>Account Total</th>
    <th>Transaction Amount</th>
  </tr>

  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= @accounts.find(transaction.account_id).id %></td>
      <td><%= @users.find(@accounts.find(transaction.account_id).user_id).name %></td>
      <td>$<%= @accounts.find(transaction.account_id).total %></td>
      <td>$<%= transaction.amount %></td>
      <td><%= link_to 'Show', transaction_path(transaction) %></td>
    </tr>
  <% end %>
</table>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= form_for :transaction, url: transactions_path do |transaction_form| %>
  <p>
    Account Owner<br>
    <%= transaction_form.select :account_id, @options %>
  </p>




  <p>
    <%= transaction_form.label :amount %><br>
    <%= transaction_form.number_field :amount %>
  </p>

  <p>
    <%= transaction_form.submit %>
  </p>
<% end %>

app/views/transactions/show.html.erb
<p>
  <strong>Transaction:</strong>
  <%= @transaction.id %>
</p>

<p>
  <strong>Starting account amount:</strong>
  <%= @account.total %>
</p>

<p>
  <strong>Transaction Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Account Owner</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Account Number:</strong>
  <%= @account.id %>
</p>

<% if @account.total < @transaction.amount %>
  <p>
    You do not have enough money in your account.
  </p>
<% else %>
  <table>
    <tr>
      <th>Number of Bills</th>
      <th>Type of Bill</th>
    </tr>

    <% @response.each do |nominalamount| %>
      <tr>
        <td><%= nominalamount[0] %></td>
        <td><%= nominalamount[1] %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for :user, url: users_path do |user_form| %>
  <p>
    <%= user_form.label :name %><br>
    <%= user_form.text_field :name %>
  </p>

  <p>
    <%= user_form.label :password %><br>
    <%= user_form.text_field :password %>
  </p>

  <p>
    <%= user_form.label :email %><br>
    <%= user_form.text_field :email %>
  </p>

  <p>
    <%= user_form.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name of New User:</strong>
  <%= @user.name %>
</p>

<p>
  <strong> Email Address:</strong>
  <%= @user.email %>
</p>